# Generated by Django 3.1.2 on 2020-12-17 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this bid across whole system', primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Enter a brief description of the bid', max_length=1000)),
                ('type_bid', models.CharField(blank=True, choices=[('h', 'hard'), ('c', 'cartridge'), ('pr', 'printer'), ('w', 'web or net'), ('t', 'telephone'), ('v', 'viruses'), ('s', 'soft'), ('pa', 'Parus')], default='h', max_length=2)),
                ('time_creation', models.DateTimeField(auto_now=True)),
                ('time_start', models.DateTimeField(null=True)),
                ('time_done', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('a', 'accepted'), ('w', 'in work'), ('f', 'finished')], default='a', max_length=1)),
                ('bider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.bider')),
                ('helper', models.ManyToManyField(null=True, to='system.Helper')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.location')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.maker')),
                ('telephone_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.telephone')),
            ],
            options={
                'ordering': ['time_creation'],
            },
        ),
    ]
