# Generated by Django 3.2 on 2021-04-17 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст объявления')),
                ('date_creation', models.DateTimeField(null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('v', 'visible'), ('h', 'hidden')], default='v', max_length=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter a brief description of the bid', max_length=1000, verbose_name='Текст заявки')),
                ('type_bid', models.CharField(blank=True, choices=[('h', 'железо'), ('c', 'картридж'), ('pr', 'принтер'), ('w', 'сеть'), ('t', 'телефон'), ('v', 'вирусы'), ('s', 'софт'), ('pa', 'Парус')], default='h', max_length=2, verbose_name='Тип заявки')),
                ('location', models.CharField(default='Кабинет', max_length=200, verbose_name='Кабинет')),
                ('telephone_num', models.CharField(default='Телефон', max_length=200, verbose_name='Телефон')),
                ('bider', models.CharField(default='', max_length=200, verbose_name='Заявитель')),
                ('helper', models.CharField(max_length=200, null=True, verbose_name='Помощник')),
                ('time_creation', models.DateTimeField(null=True, verbose_name='Дата создания заявки')),
                ('time_start', models.DateTimeField(null=True, verbose_name='Дата начала работы')),
                ('time_done', models.DateTimeField(null=True, verbose_name='Дата завершения работы')),
                ('status', models.CharField(choices=[('a', 'принята'), ('w', 'в работе'), ('f', 'выполнена')], default='a', max_length=1, verbose_name='Статус заявки')),
                ('comment', models.CharField(default='', max_length=200, verbose_name='Комментарий')),
                ('result', models.CharField(default='', max_length=300, verbose_name='Результат работы')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
