# Generated by Django 3.1.2 on 2020-12-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='helper',
            field=models.ManyToManyField(to='system.Helper'),
        ),
    ]
