# Generated by Django 3.1.5 on 2021-06-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210618_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='creator',
            field=models.CharField(default='', max_length=200, verbose_name='Принял заявку'),
        ),
    ]
