# Generated by Django 3.1.2 on 2020-12-17 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20201217_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bider',
            field=models.CharField(default='Bider', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this bid across whole system', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='location',
            field=models.CharField(default='Location', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='telephone_num',
            field=models.CharField(default='Number', max_length=200),
        ),
        migrations.DeleteModel(
            name='Bider',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Telephone',
        ),
    ]
