# Generated by Django 3.1.5 on 2021-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_bid_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='status',
        ),
        migrations.AddField(
            model_name='sticker',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст объявления'),
        ),
    ]
