# Generated by Django 3.1.2 on 2020-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20201221_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maker',
        ),
        migrations.AddField(
            model_name='bid',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bid',
            name='result',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.RemoveField(
            model_name='bid',
            name='helper',
        ),
        migrations.AddField(
            model_name='bid',
            name='helper',
            field=models.CharField(default='Helper', max_length=200),
        ),
        migrations.DeleteModel(
            name='Helper',
        ),
    ]
