# Generated by Django 3.1.2 on 2020-12-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20201221_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('a', 'принята'), ('w', 'в работе'), ('f', 'выполнена')], default='a', max_length=1),
        ),
    ]
