# Generated by Django 3.1.2 on 2021-01-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20201223_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='helper',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
