# Generated by Django 3.1.2 on 2021-01-13 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0013_sticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='sticker',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='bid',
            name='bider',
            field=models.CharField(default='', max_length=200, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='comment',
            field=models.CharField(default='', max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='helper',
            field=models.CharField(max_length=200, null=True, verbose_name='Помощник'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='location',
            field=models.CharField(default='Location', max_length=200, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='result',
            field=models.CharField(default='', max_length=300, verbose_name='Результат работы'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('a', 'принята'), ('w', 'в работе'), ('f', 'выполнена')], default='a', max_length=1, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='telephone_num',
            field=models.CharField(default='Number', max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='text',
            field=models.TextField(help_text='Enter a brief description of the bid', max_length=1000, verbose_name='Текст заявки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='time_creation',
            field=models.DateTimeField(null=True, verbose_name='Дата создания заявки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='time_done',
            field=models.DateTimeField(null=True, verbose_name='Дата завершения работы'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='time_start',
            field=models.DateTimeField(null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='type_bid',
            field=models.CharField(blank=True, choices=[('h', 'hard'), ('c', 'cartridge'), ('pr', 'printer'), ('w', 'web or net'), ('t', 'telephone'), ('v', 'viruses'), ('s', 'soft'), ('pa', 'Parus')], default='h', max_length=2, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='date_creation',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='status',
            field=models.CharField(choices=[('v', 'visible'), ('h', 'hidden')], default='v', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст объявления'),
        ),
    ]
